{% set name = "scikit-allel" %}
{% set version = "1.0.2" %}
{% set sha256 = "602d6345a3df180785ffc7515f6e47474caffa8c7db7b4b65222ea923dfbd343" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
  run:
    - python
    - numpy x.x
    - scipy
    - scikit-learn
    - numexpr
    - dask >=0.11.1
    - h5py
    - bcolz
    - zarr
    - matplotlib
    - seaborn
    - pandas

test:
  requires:
    - nose
  imports:
    - allel
    - allel.opt.model
    - allel.opt.stats
  commands:
    - nosetests -v allel --exclude=gff3

about:
  home: http://github.com/cggh/scikit-allel
  license: MIT
  license_file: LICENSE
  summary: 'A Python package for exploring and analysing genetic variation data.'
  doc_url: http://scikit-allel.readthedocs.io/
  dev_url: https://github.com/cggh/scikit-allel

extra:
  recipe-maintainers:
    - alimanfoo
    - hardingnj
