{% set name = "scikit-allel" %}
{% set version = "1.1.9" %}
{% set sha256 = "11d27a4911a0da4958ff50cbbef98b97061f0a575b838d61e020861c86ffc9f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy x.x
  run:
    - python
    - numpy x.x
    - scipy
    - scikit-learn
    - numexpr
    - dask >=0.15
    - h5py
    - bcolz
    - zarr
    - numcodecs
    - matplotlib
    - seaborn
    - pandas

test:
  requires:
    - nose
  imports:
    - allel
    - allel.opt.model
    - allel.opt.stats
    - allel.opt.io_vcf_read
    - allel.test
    - allel.test.model
    - allel.test.test_io_vcf_read
  commands:
    - python -m nose allel -v --exclude=from_gff3_region

about:
  home: http://github.com/cggh/scikit-allel
  license: MIT
  license_file: LICENSE
  summary: 'A Python package for exploring and analysing genetic variation data.'
  doc_url: http://scikit-allel.readthedocs.io/
  dev_url: https://github.com/cggh/scikit-allel

extra:
  recipe-maintainers:
    - alimanfoo
    - hardingnj
