travis:
  secure:
    BINSTAR_TOKEN: oI2z3/ww67BfJRPUpp3/dIqbmdS0tLgaUHHfCHqTfYkjhUJgNWXqqAPs+rkj/M9CjzNDF3QcahSqeaNeTEkbFwEuP9ecOWL/9n0r2aiVMppfHH9fAIXBHASVqH2c0cNeTkLlux7LpwOVZQtlC9BjmKcocS4JigQsB3q0spFriWJbBbRE4CTb6wenzdJVJ9nBhRC1nFgILEV7ZhhtjzEmHWpaD7zgvmAtshk9RTcSCDuq4OmAVDe+3iybVsqZsL9ubl0kgYR3+UOgqawaJv+jQzIwuEsU5O5mCPIZ+IjPoSZX5IERO45J9EIIaUa8/GPJndIRuX1glja92If2+j3QH0ZRZNsHPJsxntECB+noE55bDBLaMTdoHzn4BtXJo1xyOh/W32GaueQdhloyQEZn0bqkGYty1gPsJmDrj+9ljWwNoRs/dOWMSWSszhBi7zZLLU3KXw3svCOTMbbwbtsijAIld8rgdTYCk5mxzFnwmFT6EXm0oj6t8qvL54iC883A/ykQro+oliHZy0wjSfEWYYma8Yro3wP0yX9m0sTZAsvTeM9h+Glk8Bk1psTPQ4lYvuGdP2le7L4e7XLRNDBIw8MB+MFgGZrpcajtgWDdMW66KifMeY8Z7b94W30AtP7UVsmKCyUihdX+aqgYBtdXbxpYzfCfeiEZU3UIp7Bc0N4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
